settings:
  connection:
    - Telegram
    - Google
    - Mail
---
settings:
  address:
    "192.168.1.1": "8080"
    "192.168.1.2": "8081"
    "192.168.1.3": "8082"
    "192.168.1.4": "8083"
    "192.168.1.5": "8084"
---
settings:
  password: "FGLSGLKNFSDA"