spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/testdep
    user: ""

  flyway:
    url: jdbc:h2:file:~/testdep
---
DATA_STORAGE:
  SPRING_DATA_STORAGE: false
  TEMPLATE_STORAGE: false
  JPA_STORAGE: true