spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/study
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  boot:
    admin:
      client:
        url: http://localhost:8082
        instance:
          name: user-server
  flyway:
    url: jdbc:postgresql://localhost:5432/study
    user: postgres
    password: postgres
    enabled: true


logging:
  file:
    name: /var/log/user-server-application.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  level:
    ru:
      darnei:
        study: TRACE


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


storage:
  type: jpa

