spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:C:/data/sample
    user: ""

  flyway:
    user: ""
    password: ""
    url: jdbc:h2:file:~/sample
    enabled: false
    schemas: PUBLIC
---
DATA_STORAGE:
  SPRING_DATA_STORAGE: true
  TEMPLATE_STORAGE: false
  JPA_STORAGE: false