server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:8082
        instance:
          name: user-client
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always